- name: ensure system packages are installed
  apt: pkg={{ item }} state=latest
  with_items:
    - git-core
    - curl
    - wget
    - htop
    - mc
    - libpq-dev
    - build-essential
    - python-software-properties
    - unzip

- name: Add Ondřej Surý PPA
  apt_repository: repo='ppa:ondrej/php5-5.6'

- name: update apt cache
  apt: update_cache=yes

- include: ntp.yml